# Generated by Django 5.0.6 on 2024-07-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendRequest', '0002_remove_friendrequest_state_remove_friendrequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
