# Generated by Django 5.0.6 on 2024-07-02 09:31

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_about_me_user_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(default=user.models.code_generator, max_length=12),
        ),
    ]
